### ISSUE TITLE
Overview of SqlAlchemy 

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#116]
Provide API guide from http network layer to DB for developers.

 - video call early in sprint
Quick write up
extensive documentation
setup workshop or paring sessions.
 
- [x]  Part 1
- [ ]  Part 2

**Comment by ccostino** [comment]
We need to schedule a follow-up to this soon.  @PaulClark2 can you help find people's availability again for next week?  It can be another virtual session. :-)
