### ISSUE TITLE
Office hours

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-transition#129]
Carve out time for engineering (Carlo, Lindsay, Christine) to discuss code (office hours)
- [x] Routine meetings established

**Comment by ccostino** [comment]
So far we have the following:

* Carlo from 10 AM - 12 PM EST on Mondays (on-site at FEC generally)
* Vraj from 1 PM - 3 PM EST on Thursdays
* Lindsay from 10 AM - 12 PM EST on Wednesdays (on-site at GSA generally)

We have these on our FEC team calendar and will also let folks know in Slack so if they want to be added to the invite and receive calendar reminders they can.

I'll update when we finalize!

**Comment by ccostino** [comment]
Schedule has been set!  If anyone else would like calendar invites on their calendars with these so they can keep track of them with reminders and such, please just ask in Slack!
