### ISSUE TITLE
Account creation and policy needs to be streamlined

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-transition#131]
Account creation and policy needs to be streamlined
- [x] cloud.gov
- [x] New Relic
- [x] RDS
- [x] Github
- [x] Wagtail
- [x] Consolidate roles and policies

**Comment by LindsayYoung** [comment]
Laura and I proposed some copy changes and will seek input in the #ato channel

**Comment by lbeaufort** [comment]
Linked to PR: https://github.com/18F/fec-accounts/pull/64

**Comment by AmyKort** [comment]
Are we ready to close this one?

**Comment by PaulClark2** [comment]
Not sure if the PR has been merged. @lbeaufort can you confirm?

**Comment by lbeaufort** [comment]
@PaulClark2 it hasn't been merged. I don't know if it needs anything else - I tagged @LindsayYoung as a reviewer but she's out. I don't know who needs to approve it before it gets merged.

**Comment by PaulClark2** [comment]
This needs final review. I think Jay or Justin should review it too.

**Comment by AmyKort** [comment]
Is this ready to be closed?

**Comment by PaulClark2** [comment]
merged
