### ISSUE TITLE
Wireframing tool for FEC

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-transition#133]
Wireframing tool for FEC
- Sketch is not approved for FEC
- Possibly Axure?

Path 1: 
- [ ] Jonella works with UX listserv community (Liz Goodman) to establish approval path for Sketch
Path 2: 
- [ ] Use Illustrator instead of Sketch
- [ ] Jen learns to export from Sketch into Illustrator

**Comment by JonellaCulmer** [comment]
Sketch has been approved for FEC use with some caveats. SaaS cloud storage, 3rd party extensions and add-ons are not authorized. Extensions and add-ons require separate approval.
