### ISSUE TITLE
Circle CI licenses

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-transition#134]
Circle CI licenses
- [ ] Depends on being able to transfer GitHub repos to FECgov
- [ ] Figure out whether we can transfer Circle CI licenses to FEC or just hook things up directly via GitHub

**Comment by patphongs** [comment]
Need to check what current plan 18F has on CircleCI

**Comment by patphongs** [comment]
It looks like there is no need for a license for CircleCI, we just need to sign up, transfer our code to our own fecgov github repo, and then hook up Circle CI to it. It is free for our public repos. If the free version is clunky we can look into paying the monthly fees to run more containers.

![screen shot 2017-10-12 at 3 11 27 pm](https://user-images.githubusercontent.com/12799132/31514451-a9cb220c-af5f-11e7-906b-23faad3db32f.png)


![screen shot 2017-10-12 at 3 10 19 pm](https://user-images.githubusercontent.com/12799132/31514407-88f6b6d6-af5f-11e7-9ec5-eb07f12e9f5b.png)
