### ISSUE TITLE
Train FEC staff to set up elastic search locally

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-transition#135]
Set up elastic search locally

- [X] Send out survey on timing (https://beta.doodle.com/poll/geu5x2wmngrndn8b)
- [ ] Put together presentation for web team on setting up elasticsearch and loading legal docs for testing/development
- [ ] Add to /legal/ API endpoint documentation
- [ ] Show materials to @vrajmohan and get his input

**Comment by lbeaufort** [comment]
Closed in favor of https://github.com/18F/fec-transition/issues/141
