### ISSUE TITLE
Create correct teams for GitHub

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-transition#139]
Create correct teams for GitHub in fecgov organization

3 groups
- [ ] content 
- [ ] dev/engineering
- [ ] admin

**Comment by patphongs** [comment]
Teams have been created and members have been added to each individual team. Many members still need to join the organization. Those invites have been sent accordingly. 

https://github.com/orgs/fecgov/teams

**Comment by patphongs** [comment]
Closing this ticket as the teams have been created
