### ISSUE TITLE
Plan incident response and DR workshop

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#152]
Incident response. 

- [x] Security Training
- [x] Incident Response (compromised system, password leaked, etc.)

Disaster recovery

- [x] Go over Disaster recovery process
- [x] Image of box every night
- [x] do a restore to staging

**Comment by jwchumley** [comment]
Combine with DR workshop?

**Comment by LindsayYoung** [comment]
I am going to base it off of https://github.com/18F/fec-accounts/pull/50/files

I sent it to DKP for review. 

Next
 - [ ]  Check in with Jay when he is back
 - [ ]  Make slides

**Comment by LindsayYoung** [comment]
https://docs.google.com/presentation/d/1yqUCBUZ-oi5NsqOcrOrYvHNZGGyu5ADxdr93iaiX1ow/edit#slide=id.g2d280784f7_0_0

**Comment by LindsayYoung** [comment]
Done!
