### ISSUE TITLE
Walk FEC integration team through SSP

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-transition#16]
In order to get members of the FEC integration team prepared to take over the ATO, we need to walk them through the SSP.

---

Tasks:
- [x] Set up time to meet
- [ ] Hold meeting

**Comment by PaulClark2** [comment]
We'll plan to do this on 1/11/17 during our regularly scheduled integration meeting at 3:00 p.m.

**Comment by PaulClark2** [comment]
Jay and Saady would like a copy of the SSP before the meeting on the 11th.

**Comment by adrianwebb** [comment]
Need to get Jay (the CISO) the SSP document today or tomorrow.
