### ISSUE TITLE
Front-end training and documentation

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-transition#17]
In order to help Pat and John get comfortable with front-end work for with the new site, @xtine is going to work with them to get them familiarized with the system.

This will involve:
- [ ] Create a front-end specific system diagram
- [ ] Improve documentation around CSS and JS components
- [ ] Pairing sessions

**Comment by adrianwebb** [comment]
Just checking to see if this is still ongoing? cc @xtine

**Comment by xtine** [comment]
Training is for the most part done. Documentation is ongoing.

**Comment by adrianwebb** [comment]
Set a concrete time for deliverable of documentation (and figure out the needed documentation).  Carve out 30 minutes per week to discuss what is necessary (set on Friday).

**Comment by porta-antiporta** [comment]
@xtine we can close this yeah?  after the workshop you had in DC last month?

**Comment by xtine** [comment]
@porta-antiporta: yep. also with dedicated sprint on pattern library/design system, that can be a separate issue.
