### ISSUE TITLE
Develop training plan with FEC 

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-transition#19]
In order to help the FEC prepare to take over the new site, we need to work with them to develop a training plan for this quarter. 

The take-away from this issue should be a plan that:

- Identifies which skills they need to account for
- Identifies all the technologies we’re using they need to be trained on
- Identifies potential sources of training, both from 18F and outside

The main step to take with this is for me, @adrianwebb and @LindsayYoung to meet with members of the FEC leadership team to sketch this stuff out. We may pull in additional members of the team on an ad hoc basis.

**Comment by adrianwebb** [comment]
The next step is to set up a meeting to determine the process for grooming and structuring the documentation with the integration team.  Paul should be getting a meeting together next week.
