### ISSUE TITLE
Get FEC set up with their own GitHub organization

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#29]
- [x] Create an organization for FEC in GitHub
- [ ] Create initial FEC GitHub teams
- [ ] Assign administrators to FEC staff

**Comment by adrianwebb** [comment]
Expecting to have a name soon, then Paul is going to set up with my help.

**Comment by PaulClark2** [comment]
https://github.com/fecgov

**Comment by adrianwebb** [comment]
Now we just need to get the administrative teams set up.  I'll get with you @PaulClark2 Wednesday about this.
