### ISSUE TITLE
Git / GitHub training

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#30]
Train FEC integration team (possibly other staff) on how to use Git and GitHub to work with 18F developed software.

**Comment by adrianwebb** [comment]
Reach out to Paul to schedule and see who is available.

**Comment by ccostino** [comment]
@LindsayYoung and I will be coordinating soon to come up with a script for this.  The time we had set aside last Friday to do this was taken up by release prep and PR reviews (the original session was postponed until January).

**Comment by adrianwebb** [comment]
Sounds good.

**Comment by adrianwebb** [comment]
Set up one 2 hour meeting with a potential follow on this sprint.

**Comment by ccostino** [comment]
To date, @LindsayYoung and I have created the following:

* Screencasts for FEC folks walking through a quick Git commit and push example, followed but a GitHub PR review and merge example.
* [Git and SVN differences](https://github.com/18F/FEC/wiki/5.-Introduction-to-Git), which includes links to [additional reading](https://github.com/18F/FEC/wiki/5.-Introduction-to-Git#additional-resources)
* A plan for our in-person session on Thursday, which is to start with following up from the screencasts and work through https://guides.github.com/activities/hello-world/

**Comment by LindsayYoung** [comment]
We did this :)
