### ISSUE TITLE
Determine detailed FEC integration team shadowing plan

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#34]
Shadowing practices
- [ ] Product shadowing/pairing practices
- [ ] Design shadowing/pairing practices
- [ ] Engineering shadowing/pairing practices

Integrated project work
- [ ] Map out a complete process for ideation of projects FEC integration team can work on
- [ ] Project collaboration practices

Communication channels
- [ ] Determine the preferred methods of cross team communications channels

**Comment by jenniferthibault** [comment]
Are there criteria for completion on this?

**Comment by adrianwebb** [comment]
@jenniferthibault: Does the above help?

**Comment by adrianwebb** [comment]
I believe this is done now.  @noahmanger is that correct?

**Comment by noahmanger** [comment]
@adrianwebb I'd still like to discuss the plan / get feedback from the integration team before we close this out, which I believe we scheduled for tomorrow?

**Comment by adrianwebb** [comment]
Yep. Sounds good.
