### ISSUE TITLE
Design and conduct FEC Content Manager Wagtail CMS training workshops

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#35]
To get our content managers creating Wagtail pages for our compliance, we need to train them how to do this.

This will be complete when our managers can:

- [x] Create custom pages
- [x] Edit custom pages

Also could these be recorded as a screencast?

**Comment by emileighoutlaw** [comment]
Probably these could be recorded. I don't know how to do that, but I'm definitely open to doing this, if you think it'd be helpful @adrianwebb

**Comment by emileighoutlaw** [comment]
To get our content managers creating Wagtail pages for our compliance, we need to train them how to do this. 

This will be complete when our managers can:
- [ ] Create custom pages
- [ ] Edit custom pages

**Comment by emileighoutlaw** [comment]
Update— We're going to do this with Dorothy first, next week when the other managers are out of town.

Our agenda:
- Create a custom compliance page
- Edit style issues from Word Document copy/paste
- Linking to other pages
- Editing existing pages
- Publishing (and adding a password for reviewers)

**Comment by adrianwebb** [comment]
Sounds good!

**Comment by emileighoutlaw** [comment]
This is complete! We're going to revisit in a couple weeks and do a refresher course for folks

:)
