### ISSUE TITLE
PostgreSQL workshop

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#37]
@adrianwebb commented on [Mon Dec 19 2016](https://github.com/18F/fec-epics/issues/103)

Conduct a training workshop to cover the basics of PostgreSQL and how we use it on the FEC projects.

**Comment by adrianwebb** [comment]
@ccostino and @LindsayYoung: Just putting this on your radar.  Also let me know if there are others who would be comfortable giving this training?

**Comment by ccostino** [comment]
Will do, thanks @adrianwebb!

**Comment by adrianwebb** [comment]
Get with Rohan and Jean on what they need training in

**Comment by LindsayYoung** [comment]
Discussion moved to https://github.com/18F/fec-transition/issues/88
