### ISSUE TITLE
Compile Django documentation and tutorials for FEC engineers

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#39]
We need to have a way to introduce the engineers to the major principles of the Django Python framework.

**Comment by adrianwebb** [comment]
@ccostino, @LindsayYoung: Let me know your thoughts on this, and if you have feelings about who may be best to conduct the training.  Might be possible to spread parts of it between team members if it is a series of screencasts on important concepts related to Django?

**Comment by ccostino** [comment]
Hmm, this one I wonder if it might be worth finding something to guide folks to instead and then having a session or two to help support afterward.  The reason being is that there is a lot of material to cover and I don't know that we'd be able to effectively do this ourselves.

Django itself has a great [tutorial in its documentation](https://docs.djangoproject.com/en/1.10/intro/tutorial01/) (and there is also a general [getting started](https://www.djangoproject.com/start/) page there too).  [Django Girls has a great tutorial](https://tutorial.djangogirls.org/en/) as well for getting started.  If folks could start with these to build up some foundational knowledge, it'd be much easier and more effective for us to then come in and explain how it's being used in our projects (namely the CMS).

Does this sound reasonable, or am I off base at all?  I'm definitely happy to discuss further to figure out the best approach to do this!

**Comment by adrianwebb** [comment]
I completely agree with you here.  I think we can point them to documentation and materials (like tutorial videos) and cover the more 18F FEC related points in a training or videos we make.

**Comment by adrianwebb** [comment]
Possible office hours?

**Comment by LindsayYoung** [comment]
Found this list of resources: https://code.djangoproject.com/wiki/Tutorials

Found this from the list, I liked it okay: https://www.youtube.com/watch?v=oT1A1KKf0SI this focuses on installation and explains python environments. 

I like this one because it explains some terminology and web app structure:
https://www.youtube.com/watch?v=FNQxxpM1yOs

(For the videos I am skipping thorough and sampling them)

**Comment by adrianwebb** [comment]
Target having an initial list of training/tutorials by the end of the week

**Comment by ccostino** [comment]
Some discussion/coverage of setting up Python and virtual environments themselves is probably a good idea, it will likely save a lot of headaches as folks dive into other things.  The Django Girls tutorial also covers this in the beginning before getting the user setup with Django itself.

I was looking through the list and one thing to keep in mind is reference materials/tutorials that are up to date.  We're using the latest version of Django with the CMS (and will likely have Wagtail upgraded again soon enough, too) currently and a recent version of Python (3.5.2, though 3.6 just came out), so I want to make sure folks are working through things that are relevant and correct. :-)

**Comment by ccostino** [comment]
@LindsayYoung that second one seems to be pretty comprehensive, there's a [whole series](https://www.youtube.com/watch?v=FNQxxpM1yOs&list=PLQVvvaa0QuDeA05ZouE4OzDYLHY-XH-Nd) and a [companion site](https://pythonprogramming.net/django-web-development-with-python-intro/) with it.

Would it be fair to say that these are a good start?

* Django Girls tutorial (starting at the [How the Internet Works](https://tutorial.djangogirls.org/en/how_the_internet_works/) section)
* Django's official tutorial ([Writing your first Django App](https://docs.djangoproject.com/en/1.10/intro/tutorial01/))
* Pythonprogramming.net [video tutorial series](https://www.youtube.com/watch?v=FNQxxpM1yOs&list=PLQVvvaa0QuDeA05ZouE4OzDYLHY-XH-Nd)

In addition, two major resources that folks should always have at their finger tips:

* [Django 1.10's Documentation](https://docs.djangoproject.com/en/1.10/)
* [Python 3.5's Documentation](https://docs.python.org/3.5/) (going to https://docs.python.org/3/ will always take you to the latest Python 3 version)

Lastly, if folks need a bit of a Python tutorial as well, we've been using [Dive Into Python 3](http://www.diveintopython3.net/) for the #learnpython channel in 18F's Slack, it covers a lot of the basics and fairly common nuances of Python that most folks will encounter earlier on.

I think between these three tutorials which are all recently put together and the main developer resources, this is a good start for folks diving into Django.  How does this look to both of you?

**Comment by ccostino** [comment]
One other thing, if folks are looking for a more traditional book resource, [Two Scoops of Django](https://www.twoscoopspress.com/products/two-scoops-of-django-1-8) is a fantastic resource and covers a lot of general best practices for Django.  The most recent book covers Django 1.8, but the fundamentals covered will still serve folks very well!

**Comment by ccostino** [comment]
There is also [The Hitchhiker's Guide to Python](http://docs.python-guide.org/en/latest/) - this is online and now in book form via O'Reilly.  It's compiled by [Kenneth Reitz](https://www.kennethreitz.org/), who has written a slew of Python packages that most of us have come to rely on and are very thankful for. :-)

**Comment by ccostino** [comment]
@adrianwebb:  Fair enough to mark this done at this point?  Is there anything else required for this not here yet?

**Comment by ccostino** [comment]
I created a Google doc with these links that we can share out.

**Comment by adrianwebb** [comment]
Looks good to me.

**Comment by ccostino** [comment]
Shared in the partners Slack channel!
