### ISSUE TITLE
Initiate shadowing / pairing practice for the FEC integration team

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#40]
Implement the shadowing practices outlined in the integration plan developed as part of this issue: https://github.com/18F/fec-transition/issues/34

- [ ] Product shadowing / pairing
- [ ] Design shadowing / pairing
- [ ] Engineering shadowing / pairing

**Comment by jenniferthibault** [comment]
@adrianwebb , questions that occurred to me during sprint planning: if the FEC doesn't have any designers right now, who would we be pairing with? What disciplines does this issue intend to cover? Content design? UX? Visual? Front end?

**Comment by adrianwebb** [comment]
Dependent on this: https://github.com/18F/fec-transition/issues/34
