### ISSUE TITLE
Get FEC Sharepoint accounts set up for 18F team members

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#41]
We need to ensure we can start adding and editing FEC documents

- [ ] Create accounts for 18F team members
- [ ] Train us or point us to documentation on using Sharepoint

**Comment by jwchumley** [comment]
It's actually all set up but I'm holding on it because there is some question as to how and whether it is being backed up and I want to resolve that before we start putting documents in it.



________________________________

**Comment by adrianwebb** [comment]
Still need to figure this one out.  Need GSA account access (not Microsoft accounts)
