### ISSUE TITLE
Ensure FEC integration team has the collaboration / development tools they need to do their job

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#43]
This includes:

- [ ] Videoconferencing
- [ ] Slack or group based chat
- [ ] Document collaboration
- [ ] GitHub organization and membership

**Comment by PaulClark2** [comment]
I set up https://github.com/fecgov today.  I invited the integration team and the entire 18F/FEC team to the organization.

**Comment by PaulClark2** [comment]
@adrianwebb sent invitations for Slack to members of the integration team not already on Slack.  

I still need to do a head count of initial FEC users for FEC's Slack account.

**Comment by adrianwebb** [comment]
Working on a Mac justification document now for the FEC.
