### ISSUE TITLE
Travis CI overview

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#47]
We need to create documentation around how our Travid CI setup works.  This could be combined with documentation we find.

**Comment by adrianwebb** [comment]
So @LindsayYoung and @ccostino, just putting this on your radar.  This might tie in with the cloud.gov deployment training?

**Comment by ccostino** [comment]
Yes, it very much would as we leverage Travis CI to do the bulk of our deployments to cloud.gov automatically.  Thankfully this is fairly straightforward, I think a possible outline would look like this:

* What is Travis CI?
* How is Travis CI connected to our repos?
   * Setting up services in a GitHub repo
   * The `travis.yml` file
* Additional information and resources (e.g., Travis CI's documentation)

@adrianwebb I know you're moving and consolidating some of the documentation we have scattered around in the wikis to another spot, should this be added to that destination?

**Comment by ccostino** [comment]
We completed this work as a part of our Git and Git Flow workshop last week.  A section of it covered Travis CI (what it is, how it works, and where to find information).  I'm closing this in favor of diving into more detail at a later time when we dig more into how deployments on cloud.gov work with manifest files (e.g., #31, which goes into more detail than what we have so far).
