### ISSUE TITLE
Ethnio training

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#48]
Need to make sure FEC knows how to work with Ethnio

**Comment by nickykrause** [comment]
@adrianwebb: I think this one is done. Ethan and I held a session with @patphongs to walk her though how a screener is set up in Ethnio. 

We can also do some Q&A once the FEC gets their own Ethnio account set up, but I think Pat has knowledge of the basics.

**Comment by adrianwebb** [comment]
Gotcha, that sounds good.
