### ISSUE TITLE
Usability test documentation

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#50]
Document our processes for usability testing on the FEC projects.

**Comment by nickykrause** [comment]
Completed via:
![fec-testing-process](https://cloud.githubusercontent.com/assets/1450173/26063382/815033f8-3953-11e7-956d-bef17595f3b9.png)

**Comment by adrianwebb** [comment]
That is a beautiful diagram @nickykrause!!

**Comment by nickykrause** [comment]
Thanks @adrianwebb! I :heart: diagrams :)
