### ISSUE TITLE
Overview Agile/Scrum training for the FEC

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-transition#57]
FEC is new to Agile.  Let's deliver our Agile 10x series to the FEC; first round in April before Leading SAFe training.

- [x] Recruit coaches
- [x] Send invites to FEC attendees
- [x] Host the training
- [ ] Get feedback from attendees
- [ ] Consider changes for future sessions

**Comment by PaulClark2** [comment]
Training completed. Slides in #agile-class Slack channel.,
