### ISSUE TITLE
Flesh out Onboarding docs for people new to the team

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#60]
This is for onboarding technical team members covering things like setting up environments, learning tools, identifying admins etc.

Completion criteria: Onboarding docs completed and cataloged.

**Comment by jwchumley** [comment]
Needs more people's eyes on this.

**Comment by LindsayYoung** [comment]
https://docs.google.com/document/d/18ZjPvNrdW3wn9pUx7hSNbaMlaEaPPOGzOHh-WjLiVOg/edit#

**Comment by jwchumley** [comment]
Need more people to look at this.

**Comment by LindsayYoung** [comment]
I think these are in pretty good shape for engineering, we can always add more later, so I am closing for now
