### ISSUE TITLE
Documentation and example workflows for working with code repos in github and locally

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#63]
Documentation and example workflows for working with code repos in github and locally

Completion criteria: ?

**Comment by jwchumley** [comment]
Add to onboarding documentation.

**Comment by ccostino** [comment]
I've started adding specific commands and a general flow of events when working with the code and GitHub to the onboarding doc in addition to what is already present.  As always, extra eyes on this would be much appreciated!  Any questions folks have or call-outs to things that don't make sense will help round this out much more.

**Comment by ccostino** [comment]
The specific section is here: https://docs.google.com/document/d/18ZjPvNrdW3wn9pUx7hSNbaMlaEaPPOGzOHh-WjLiVOg/edit#heading=h.6bm1gbax8nqe

**Comment by ccostino** [comment]
@LindsayYoung do you feel there are more workflows that we should document after our workshop last week, or does what we put together cover enough?  I will ask in FEC Slack as well to see how folks feel.

**Comment by ccostino** [comment]
This work has taken shape in a couple of different ways:  we've created some additional docs and slides in the shared drive folder for training over the last few months, and a bunch of updates are going to be going into the `fec-cms` repo with https://github.com/18F/fec-cms/pull/1495 very soon that cover the workflows right in the project documentation itself.

Shall we close this issue, @PaulClark2?
