### ISSUE TITLE
Workshop - Using Gitflow for hotfixes or deployment

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#64]
Using Gitflow for hotfixes or deployment

Criteria: Complete workshop

**Comment by jwchumley** [comment]
Accidentally closed

**Comment by jwchumley** [comment]
@jeff - set up screen sharing session for week after Mac setup.

**Comment by ccostino** [comment]
@jwchumley is this something we can still schedule at some point this week?  @LindsayYoung and I can coordinate to determine our availability if so.

**Comment by ccostino** [comment]
We ran our workshop with lots of great questions and had a successful live deployment demo! :-)
