### ISSUE TITLE
Finish building v1 of pattern library

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#66]
@xtine @jenniferthibault Please fill in details here

**Comment by jenniferthibault** [comment]
To me this would be accomplished through completing the following issues:
- [Figure out what format Styles will take in the pattern library guidance #733](https://github.com/18F/fec-style/issues/733)
- [Figure out what format Templates will take in the pattern library guidance #734](https://github.com/18F/fec-style/issues/734)
- [Clean up SCSS files for Pattern Library #725](https://github.com/18F/fec-style/issues/725)

Which are all in progress in the front-end implementation stage

**Comment by xtine** [comment]
Tasks for me to complete:
- [ ] Finish building out documentation pages
- [ ] Get documentation pages working on live server
- [ ] Review current components if anything is additional is needed

**Comment by AmyKort** [comment]
This is complete for the work we need right now. As we continue to grow the pattern library, we'll add new issues for specific items.
