### ISSUE TITLE
Legal Elastic Search training - overview/basics

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#75]
Short 1 or 2 hr video chat with Tony or Vraj. Record session from desktop for future reference.

Completion: Training session is done.

**Comment by vrajmohan** [comment]
Does 10:00-11:30am PDT on Wednesday the work for everyone for this session? If no one objects, I will send a calendar invite.

**Comment by vrajmohan** [comment]
I've sent the meeting invite. Please add anyone else who should be included.

**Comment by vrajmohan** [comment]
Completed. Presentation - [Elasticsearch.pdf](https://github.com/18F/fec-transition/files/1178234/Elasticsearch.pdf)
