### ISSUE TITLE
Plan Infrastructure training

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#77]
Plan infrastructure training

Completion:  Infrastructure training plan is in place

**Comment by PaulClark2** [comment]
- [ ] Rohan
- [ ] Jun
- [ ] Helen

**Comment by LindsayYoung** [comment]
Started a draft here:
https://docs.google.com/document/d/1dPiq4-IFNkM7rDm0hNi6BsakGBtxDcj_U8P5ZFM0p9M/edit#
