### ISSUE TITLE
Log training - Kibana, cf logs

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#84]
Pat reach out to Peter at Cloud.gov about training.

invite Chris and Gashaw

**Comment by patphongs** [comment]
Reached out to @pburkholder and he suggested the cloud.gov team set up regular "Office Hours" so that the team can ask about common features of the kibana system and how we can make it work better for our project.

**Comment by LindsayYoung** [comment]
It looks like Lauren Ancona is willing to do a training for us! She is great with Kibana. I will see if we can get her some dev data to work with. She can give us an overview and show us how to set up some custom dashboards!

**Comment by patphongs** [comment]
Please add to the training how to tail logs and check apps and services:

cf logs, cf apps, cf services

**Comment by PaulClark2** [comment]
- [ ] Priya
- [ ] Rohan
- [ ] Helen
- [ ] Jun

**Comment by pburkholder** [comment]
Thanks for the update.

**Comment by patphongs** [comment]
Please add me to the list of interested too, thanks!

**Comment by LindsayYoung** [comment]
Update: Lauren Ancona has made some slides and I am going to touch base with her this week, then we can to scheduling
