### ISSUE TITLE
Create ability for content managers to implement GovDelivery sign-ups

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#97]
Create ability for content managers to implement GovDelivery sign-ups appropriate to the page they're managing in Wagtail.

@jameshupp - can you add anything here?

dependency - design gov delivery integration with pages

Completion Criteria: Content manager can easily list their selected pages on GovDelivery

A few tickets from FEC-CMS that is connected to govdelivery
https://github.com/18F/fec-cms/issues/1090
https://github.com/18F/fec-cms/issues/1044

**Comment by jameshupp** [comment]
The related FEC-CMS tickets listed above I _think_ have dependencies on each other, and it goes like this:

https://github.com/18F/fec-cms/issues/1090 should be signed off independently.
https://github.com/18F/fec-cms/issues/1121 is in progress, but it depends on https://github.com/18F/fec-cms/issues/1090 to be finalized.
https://github.com/18F/fec-cms/issues/1044 can get started with some preliminary work on https://github.com/18F/fec-cms/issues/1121, but the latter needs to be completed before we can validate the former.

And then, once we have a designed signup (1044) that works on the right pages (1121) for the right set of lists (1090), it can be implemented in Wagtail.
